### ISSUE TITLE
Fix lighting shit

### ISSUE THREAD

**Issue by NPException42** [NPException42/Dimensional-Pockets#14]
simplest option (probably):
* always add 2 instead of 1 to chunk-Y on room generation.
* if the current X is even, start at Y=0, otherwise start at Y=1

That way we loose 8 rooms from a chunk, but that "should" fix the issue, without the need to touch any other code than the room generation.

**Comment by Jezza** [comment]
Didn't you just lose your shit at this and decide to close it?

**Comment by NPException42** [comment]
I have put the todo in a new issue, to clarify things: #41
