### ISSUE TITLE
Server stuck in a startup loop

### ISSUE THREAD

**Issue by BBoldt** [NPException42/Dimensional-Pockets#31]
This is kind of a weird one, the server seems to crash when loading a dimensional pocket which has IC2 stuff set up inside.

http://pastebin.com/N7xk3vaq

Forge 1107
Latest dimensional pockets
industrialcraft-2-2.2.633-experimental.jar

My setup looks like this:
http://i.imgur.com/P6Zwg4n.jpg

I can fix it by removing the IC2 machines and wires with MC Edit.

**Comment by Jezza** [comment]
Ok, we're all back and working on it.
We'll have a build out for you to test shortly. :D
Sorry for the massive delay.

**Comment by NPException42** [comment]
Hey @BBoldt, this issue is a bit old now, so  I wonder if you can reproduce the issue with the current version?

**Comment by BBoldt** [comment]
Not really in a position to test it or try and reproduce it currently.

**Comment by NPException42** [comment]
Okay. Well, I close this for now then. If you encounter it in the future, feel free to open up a new issue :)
