### ISSUE TITLE
RF Support: New textures for the Dimensional Pocket if configured for energy transfer

### ISSUE THREAD

**Issue by NPException42** [NPException42/Dimensional-Pockets#38]
The Dimensional Pocket block needs 2 additional textures:
* One for RF input mode (with blue-ish stuff so to match the well-known coloring scheme of Thermal Expansion)
* One for RF output mode (red-orange-ish stuff, to match Thermal Expansion coloring scheme)

**Comment by Jezza** [comment]
I'll probably do this as apart of the render.
So we'll just need textures for that.

**Comment by NPException42** [comment]
well this is pretty much done. its just a question of color now.
