### ISSUE TITLE
List of shit to do first.

### ISSUE THREAD

**Issue by Jezza** [NPException42/Dimensional-Pockets#42]
* [ ] Make the gui a more relevant and intuitive process.
* [x] Finish rendering.
     * [x] Finish the item renderer.
     * [x] Render the appropriate FlowState colour with the pocket.
     * [x] Redo the inside of the pocket.
          * [x] Make it fancy. - Similar to the pocket block itself.

**Comment by Jezza** [comment]
I disagree that it's fancy. I'm going to need a picture if it's not the same as the one on the readme.

**Comment by NPException42** [comment]
![DP Inside 1](http://media-elerium.cursecdn.com/attachments/18/663/quarry2.png)
![DP Inside 2](http://media-elerium.cursecdn.com/attachments/18/664/quarry3.jpg)

There you go.

Side note: I was kind of said when I woke up today, and all I got in my Inbox was kind of negative comments from you. Despite me finally getting 0.10.0 out there, and having not slept more than 4 hours a day for a week now to get it done...

**Comment by Jezza** [comment]
Oh, they weren't negative comments. They were feedback, and on one case a derp from me. :P

CONGRATULATIONS! 
I'm actually impressed you got it working and managed to understand OmnisCore well enough to utilise. 
Very few people would be capable of that. 
I think you've done an  excellent job. 
I can trust your code now... :P

**Comment by Jezza** [comment]
As a side note, it looks great.
I was going off the picture from the readme.

**Comment by NPException42** [comment]
Thanks :)

You mean the picture from the release page? That is just wool, so the block and items are as visible as it can get.

**Comment by Jezza** [comment]
I thought that was weird, because last time did you take a picture while inside the pocket?

**Comment by NPException42** [comment]
Yeah, and I did that here too. I just covered floor and walls with a bit of wool ^^

**Comment by Jezza** [comment]
Haha, just cover up our greatest achievement. :P

**Comment by NPException42** [comment]
I figured that the magic moment of standing inside a pocket for the first time should not be spoiled by the title image ^^

**Comment by Jezza** [comment]
You spoiled it for me! :O

**Comment by Jezza** [comment]
Well, the GUI is completely irrelevant now, so I'm closing this.
I've finally fixed a lot of your rendering stuffs.
It's a fuck-ton cleaner now. :P

**Comment by NPException42** [comment]
\o/

**Comment by Jezza** [comment]
FYI, latest OmnisCore is broken because my git is being derpy.
Attempting to fix it now...
(Just in case you wanted to look at it. :))
