### ISSUE TITLE
Last bug before release: Guide -> messed up Titles in Crystal recipes 

### ISSUE THREAD

**Issue by NPException42** [NPException42/Dimensional-Pockets#46]
Any idea, @Jezza ?

![d3dd4100b3 1](https://cloud.githubusercontent.com/assets/6052580/5893442/a4dfa2be-a4e4-11e4-85e4-3b0a723f8708.jpg)

**Comment by NPException42** [comment]
It's just the crystal recipes, the block recipe is fine. It is also independent of the order of the recipe pages.

**Comment by Jezza** [comment]
Probably something being re-enabled that we need. 
Try commenting out the render code for the ItemStacks. It should be inside of GuiItemStack or whatever I called it. 
Assuming the text fixes itself, GuiAbstract is the start of the rabbit hole. It renders the itemStacks for us, but it's just a bridge method, so poke into the super method inside of GuiContainer, you'll see that it enables and disables various caps with gl, un-comment out the code that renders the itemStacks, and see if you can re-enable or re-disable something that the render plays with. 
Just throw a single call after the render inside the button to check which to re-enable/re-disable.

**Comment by Jezza** [comment]
Oh, wait, we're not even using OmnisCore for rendering itemStacks... Well, same still applies.
You can see what it enables and disables, so try to work out what affects what.

**Comment by Jezza** [comment]
There's a glDisable and right away, glEnable of the same thing... Probably want to make sure the lighting is ruining the text.

**Comment by NPException42** [comment]
I'll take a look at it

**Comment by NPException42** [comment]
worked around
