### ISSUE TITLE
DP Walls can be middle clicked and placed in creative.

### ISSUE THREAD

**Issue by NPException42** [NPException42/Dimensional-Pockets#52]
A comment from the MC forums:

> [...] the inside walls of the pocket dimension can be middle clicked in creative, and then placed. The blocks placed this way are invisible and can't be destroyed, which is an issue.

**Comment by Jezza** [comment]
getPickedBlock() override and return nothing. 
Though that wouldn't stop someone spawning it in, in which case, they've gone out of their way to place it, so they should probably just be banned, etc...

**Comment by NPException42** [comment]
I should be able to to prevent the block from being placed by using the block-item.

If they use the /setBlock command, it's their own fault. Also it is possible to change "can_break_pocket_wall_in_creative" to true in the config.

**Comment by Jezza** [comment]
Oh, you. Thinking of everything... 
And making configs like crazy... :P

**Comment by NPException42** [comment]
I LOVE MAKING CONFIGS! OMNIS CORE GALORE :D

**Comment by Jezza** [comment]
It's soooo easy to, at this point, it's probably hard NOT too.
