### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by williewillus** [NPException42/Dimensional-Pockets#53]
Is it possible that a config be added to change the walls of the pocket to a static texture? Having the ender starfield on all sides is lagging out my barely microwave laptop. (normally get 40fps in the overworld with 80 mods)

I'm enjoying the mod so far, thank you!

**Comment by NPException42** [comment]
sounds like a very reasonable request. I remember the days when I could hardly get 20 fps on in vanilla on my old laptop

**Comment by NPException42** [comment]
This is done. I will pack a release that includes the changes tomorrow.
You could then try to decrease the number of rendered particle planes, and just switch to the static texture if that still isn't enough.
IMO even a single moving plane looks better than the static texture. :)

**Comment by NPException42** [comment]
@williewillus, I just uploaded a small bugfix release which also has the new config options added.

You can get it on [CurseForge](http://minecraft.curseforge.com/mc-mods/226990-dimensional-pockets) (v0.10.1)
