### ISSUE TITLE
[BUG] If a DP is broken by a BC quarry, the mined item does not have proper NBT

### ISSUE THREAD

**Issue by NPException42** [NPException42/Dimensional-Pockets#56]
This is because it does not enter the onBlockRemoval() method of the TileEntity.

This also leads to the Pocket not being linked to a valid source block anymore because the relevant NBT data is not added to the ItemStack. The pocket is then for ever.

**Comment by NPException42** [comment]
Any ideas @Jezza ?

**Comment by Jezza** [comment]
Hmm, I suppose we should probably check how buildcraft destroys the block. I have no minecraft code with me, but first thing to do would be check to see if world.setBlockToAir() leads to any block notification methods. By the sounds of it, we could be missing another method that notifies the block of its destruction.

**Comment by NPException42** [comment]
Since pocket rooms are always loaded or unloaded now, the Chunkloading part of this issue doesn't matter anymore.

For the Item-without-NBT issue, I can start looking here: https://github.com/BuildCraft/BuildCraft/blob/6.5.x/common/buildcraft/core/lib/utils/BlockMiner.java
