### ISSUE TITLE
[BUG] Dropped DP as Item on ground does not render particle fields properly

### ISSUE THREAD

**Issue by NPException42** [NPException42/Dimensional-Pockets#58]
To make the problem visible, put a DP onto a Arcane Pedestal from Thaumcraft4

**Comment by NPException42** [comment]
I made the item use the static particle field for now. But this should be fixed

**Comment by NPException42** [comment]
the longer I think about it, the more i think that item-DPs should never render the fancy field. Its just too small anyway

**Comment by Jezza** [comment]
:/ this is what I did when I first made it... :P

**Comment by NPException42** [comment]
Yeah :/
But now it has at least a texture that is closer to the look of the real particle field ^^

**Comment by Jezza** [comment]
Are you saying mine wasn't the best? :P
