### ISSUE TITLE
Ender IO Traveler's Wand can teleport you through the pocket walls.

### ISSUE THREAD

**Issue by NPException42** [NPException42/Dimensional-Pockets#59]
Compact Machines has that problem somehow fixed already, I think. So maybe @thraaawn can give a hint on this?

**Comment by thraaawn** [comment]
Welp, at first i reported a few "hey your block is breakable" and "hey you allow teleporting through unbreakable blocks", but in the end I had to go the more drastic route and implement a tick handler for that.
You will need to know where your player should be and what size the pocket has. Then it's a simple positional check, see https://github.com/thraaawn/CompactMachines/blob/master/src%2Fmain%2Fjava%2Forg%2Fdave%2FCompactMachines%2Fhandler%2Fmachinedimension%2FMachineHandler.java#L60

**Comment by Jezza** [comment]
Seems almost overkill...   
Is the wand just a click in any direction, or do you have to click on blocks to tell it to pass through this wall in this direction?

**Comment by thraaawn** [comment]
Just click in any direction and it blinks you there, same as with Ender Pearls.

**Comment by NPException42** [comment]
@thraaawn maybe you are interested in this. Preventing the EIO staff and enderpearls from being used turned out to be quite simple. Still quite drastic, but it works without having to tp the player back inside. :)

If you are interested, take a look here:

[InsidePocketEventHandler.java](https://github.com/NPException42/Dimensional-Pockets/blob/master/java/net/gtn/dimensionalpocket/common/event/InsidePocketEventHandler.java) and [ClientEventHandler.java](https://github.com/NPException42/Dimensional-Pockets/blob/master/java/net/gtn/dimensionalpocket/client/event/ClientEventHandler.java)
