### ISSUE TITLE
Give NP a break.

### ISSUE THREAD

**Issue by Jezza** [NPException42/Dimensional-Pockets#67]
NP has done an AMAZING job, and now he deserves a break.
So, now that I'm back, it's time to kick it up a notch.
:D

* [x] NP taking a break.

**Comment by NPException42** [comment]
Thanks! 

Already taking a break since the release of 0.10.4 :D

What do you want to work on now that you're back? Fluids plz? ^^

**Comment by gellegbs** [comment]
Have a good valentines weekend. Don't forget guys!

**Comment by Jezza** [comment]
No longer allowed a break.
Get back to work. :P

**Comment by NPException42** [comment]
Now you got me.
