### ISSUE TITLE
Texture issue while in pocket

### ISSUE THREAD

**Issue by phlargh** [NPException42/Dimensional-Pockets#72]
I don't know if this issue has been brought up already, but if you have night vision while in the pocket all the textures turn black.  Using 0.10.4.

**Comment by NPException42** [comment]
sorry for the laaaaaate reply @phlargh, but can you reproduce this with DP as the only mod?
I cannot reproduce this with 0.10.4 myself.

Do you have other mods installed, and if so, can you provide me a list?

**Comment by NPException42** [comment]
If you can still reproduce this with the latest version, leave a comment here with a list of the mods you are using.

Closed for now.
