### ISSUE TITLE
Crash - Abstract Method Error

### ISSUE THREAD

**Issue by Cooolaid** [NPException42/Dimensional-Pockets#73]
Created a Dimensional Pocket Book and got back this crash as soon as I tried to open the book.
using v0.10.4 - In v1.7.10-mc
http://pastebin.com/zCdJWPyd

.

**Comment by NPException42** [comment]
Thanks for the report first! :)

We already know about that issue: #71 

It is in fact a problem not with DP but within Omnis Core. Jezza will fix that once he has his PC sent over to Germany, which might take a few weeks still, unfortunately.

**Comment by Cooolaid** [comment]
aah ok. thank you.  :)
