### ISSUE TITLE
Make blast resistance of Dimensional Pocket configurable

### ISSUE THREAD

**Issue by hanakocz** [NPException42/Dimensional-Pockets#74]
Hi,
I am building new modpack and using your nice mod for protection of users possesions....however:
I managed to block nonowners to enter the cube by LWC (you need to /cmodify to be able to get in someone's else cube) , however....some custom weapons and so can destroy the cube by explosion.
So I would like to be able to change blast resistance of the cube to similar number as bedrock has (so no explosion ever can destroy it, even IC2 nuke etc), however mining it by pickaxe etc would be still fine...
Can you add some config for this, or let it be more blast proof ?
Thanks

**Comment by NPException42** [comment]
The Dimensional Pocket's ability to be destroyed by an explosion was chosen on purpose. So I won't change the blast resistance in code.

What I can do however, is to make it's blast resistance changeable via config.

**Comment by NPException42** [comment]
took me a while, but this is now done for the next release
