### ISSUE TITLE
the moment I placed one it crashed my server

### ISSUE THREAD

**Issue by Starless2001** [NPException42/Dimensional-Pockets#80]
I'm trying to remove the mod and save the world. initialization gets stuck though. What info do you need? like mod/plugins list, crash reports, logs, etc.

update: after removing the mod I was able to initialize the server correctly.

**Comment by NPException42** [comment]
First, thanks for the report! :)

I would need at least the server's crash log from when you placed the Dimensional Pocket in the world.

**Comment by Starless2001** [comment]
here:

https://www.dropbox.com/s/6lc67vza4lstf8k/crash-2015-07-03_21.12.51-server.txt?dl=0

**Comment by NPException42** [comment]
I see the problem. You use OmnisCore *0.0.6*. But DimensionalPockets requires OmnisCore *0.0.5*, and only 0.0.5 for now, as stated on our [Curse  Page](http://minecraft.curseforge.com/mc-mods/226990-dimensional-pockets) and our [MC-Forum Post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2340898-dimensional-pockets). :)

**Comment by NPException42** [comment]
I'll change the Curse-Page and MC-Forum Post description a bit, since this seems to confuse quite some people.
